name: Docker Image CI

on:
  push:
    branches: [ "v1.7" ]
  pull_request:
    branches: [ "v1.7" ]

env:
  DOCKERHUB_PLATFORMS: linux/amd64,linux/arm64
  BBSD_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/lbbs-bbsd

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      id: build-bbsd
      uses: docker/build-push-action@v5
      with:
        platforms: ${{ env.DOCKERHUB_PLATFORMS }}
        context: .
        file: Dockerfile/dockerfile.bbsd
        tags: |
          ${{ env.BBSD_IMAGE }}:dev
        labels: ${{ steps.meta.outputs.labels }}
